const std = @import("std");

pub const c = @import("gdextension_cimport.zig");

pub var ci: Interfaces = undefined;
pub var get_proc_address: c.GDExtensionInterfaceGetProcAddress = undefined;
pub var library: c.GDExtensionClassLibraryPtr = undefined;

pub const Interfaces = struct {
    get_godot_version2: c.GDExtensionInterfaceGetGodotVersion2,
    mem_alloc: c.GDExtensionInterfaceMemAlloc,
    mem_realloc: c.GDExtensionInterfaceMemRealloc,
    mem_free: c.GDExtensionInterfaceMemFree,
    print_error: c.GDExtensionInterfacePrintError,
    print_error_with_message: c.GDExtensionInterfacePrintErrorWithMessage,
    print_warning: c.GDExtensionInterfacePrintWarning,
    print_warning_with_message: c.GDExtensionInterfacePrintWarningWithMessage,
    print_script_error: c.GDExtensionInterfacePrintScriptError,
    print_script_error_with_message: c.GDExtensionInterfacePrintScriptErrorWithMessage,
    get_native_struct_size: c.GDExtensionInterfaceGetNativeStructSize,
    variant_new_copy: c.GDExtensionInterfaceVariantNewCopy,
    variant_new_nil: c.GDExtensionInterfaceVariantNewNil,
    variant_destroy: c.GDExtensionInterfaceVariantDestroy,
    variant_call: c.GDExtensionInterfaceVariantCall,
    variant_call_static: c.GDExtensionInterfaceVariantCallStatic,
    variant_evaluate: c.GDExtensionInterfaceVariantEvaluate,
    variant_set: c.GDExtensionInterfaceVariantSet,
    variant_set_named: c.GDExtensionInterfaceVariantSetNamed,
    variant_set_keyed: c.GDExtensionInterfaceVariantSetKeyed,
    variant_set_indexed: c.GDExtensionInterfaceVariantSetIndexed,
    variant_get: c.GDExtensionInterfaceVariantGet,
    variant_get_named: c.GDExtensionInterfaceVariantGetNamed,
    variant_get_keyed: c.GDExtensionInterfaceVariantGetKeyed,
    variant_get_indexed: c.GDExtensionInterfaceVariantGetIndexed,
    variant_iter_init: c.GDExtensionInterfaceVariantIterInit,
    variant_iter_next: c.GDExtensionInterfaceVariantIterNext,
    variant_iter_get: c.GDExtensionInterfaceVariantIterGet,
    variant_hash: c.GDExtensionInterfaceVariantHash,
    variant_recursive_hash: c.GDExtensionInterfaceVariantRecursiveHash,
    variant_hash_compare: c.GDExtensionInterfaceVariantHashCompare,
    variant_booleanize: c.GDExtensionInterfaceVariantBooleanize,
    variant_duplicate: c.GDExtensionInterfaceVariantDuplicate,
    variant_stringify: c.GDExtensionInterfaceVariantStringify,
    variant_get_type: c.GDExtensionInterfaceVariantGetType,
    variant_has_method: c.GDExtensionInterfaceVariantHasMethod,
    variant_has_member: c.GDExtensionInterfaceVariantHasMember,
    variant_has_key: c.GDExtensionInterfaceVariantHasKey,
    variant_get_object_instance_id: c.GDExtensionInterfaceVariantGetObjectInstanceId,
    variant_get_type_name: c.GDExtensionInterfaceVariantGetTypeName,
    variant_can_convert: c.GDExtensionInterfaceVariantCanConvert,
    variant_can_convert_strict: c.GDExtensionInterfaceVariantCanConvertStrict,
    get_variant_from_type_constructor: c.GDExtensionInterfaceGetVariantFromTypeConstructor,
    get_variant_to_type_constructor: c.GDExtensionInterfaceGetVariantToTypeConstructor,
    variant_get_ptr_internal_getter: c.GDExtensionInterfaceGetVariantGetInternalPtrFunc,
    variant_get_ptr_operator_evaluator: c.GDExtensionInterfaceVariantGetPtrOperatorEvaluator,
    variant_get_ptr_builtin_method: c.GDExtensionInterfaceVariantGetPtrBuiltinMethod,
    variant_get_ptr_constructor: c.GDExtensionInterfaceVariantGetPtrConstructor,
    variant_get_ptr_destructor: c.GDExtensionInterfaceVariantGetPtrDestructor,
    variant_construct: c.GDExtensionInterfaceVariantConstruct,
    variant_get_ptr_setter: c.GDExtensionInterfaceVariantGetPtrSetter,
    variant_get_ptr_getter: c.GDExtensionInterfaceVariantGetPtrGetter,
    variant_get_ptr_indexed_setter: c.GDExtensionInterfaceVariantGetPtrIndexedSetter,
    variant_get_ptr_indexed_getter: c.GDExtensionInterfaceVariantGetPtrIndexedGetter,
    variant_get_ptr_keyed_setter: c.GDExtensionInterfaceVariantGetPtrKeyedSetter,
    variant_get_ptr_keyed_getter: c.GDExtensionInterfaceVariantGetPtrKeyedGetter,
    variant_get_ptr_keyed_checker: c.GDExtensionInterfaceVariantGetPtrKeyedChecker,
    variant_get_constant_value: c.GDExtensionInterfaceVariantGetConstantValue,
    variant_get_ptr_utility_function: c.GDExtensionInterfaceVariantGetPtrUtilityFunction,
    string_new_with_latin1_chars: c.GDExtensionInterfaceStringNewWithLatin1Chars,
    string_new_with_utf8_chars: c.GDExtensionInterfaceStringNewWithUtf8Chars,
    string_new_with_utf16_chars: c.GDExtensionInterfaceStringNewWithUtf16Chars,
    string_new_with_utf32_chars: c.GDExtensionInterfaceStringNewWithUtf32Chars,
    string_new_with_wide_chars: c.GDExtensionInterfaceStringNewWithWideChars,
    string_new_with_latin1_chars_and_len: c.GDExtensionInterfaceStringNewWithLatin1CharsAndLen,
    string_new_with_utf8_chars_and_len: c.GDExtensionInterfaceStringNewWithUtf8CharsAndLen,
    string_new_with_utf8_chars_and_len2: c.GDExtensionInterfaceStringNewWithUtf8CharsAndLen2,
    string_new_with_utf16_chars_and_len: c.GDExtensionInterfaceStringNewWithUtf16CharsAndLen,
    string_new_with_utf16_chars_and_len2: c.GDExtensionInterfaceStringNewWithUtf16CharsAndLen2,
    string_new_with_utf32_chars_and_len: c.GDExtensionInterfaceStringNewWithUtf32CharsAndLen,
    string_new_with_wide_chars_and_len: c.GDExtensionInterfaceStringNewWithWideCharsAndLen,
    string_to_latin1_chars: c.GDExtensionInterfaceStringToLatin1Chars,
    string_to_utf8_chars: c.GDExtensionInterfaceStringToUtf8Chars,
    string_to_utf16_chars: c.GDExtensionInterfaceStringToUtf16Chars,
    string_to_utf32_chars: c.GDExtensionInterfaceStringToUtf32Chars,
    string_to_wide_chars: c.GDExtensionInterfaceStringToWideChars,
    string_operator_index: c.GDExtensionInterfaceStringOperatorIndex,
    string_operator_index_const: c.GDExtensionInterfaceStringOperatorIndexConst,
    string_operator_plus_eq_string: c.GDExtensionInterfaceStringOperatorPlusEqString,
    string_operator_plus_eq_char: c.GDExtensionInterfaceStringOperatorPlusEqChar,
    string_operator_plus_eq_cstr: c.GDExtensionInterfaceStringOperatorPlusEqCstr,
    string_operator_plus_eq_wcstr: c.GDExtensionInterfaceStringOperatorPlusEqWcstr,
    string_operator_plus_eq_c32str: c.GDExtensionInterfaceStringOperatorPlusEqC32str,
    string_resize: c.GDExtensionInterfaceStringResize,
    string_name_new_with_latin1_chars: c.GDExtensionInterfaceStringNameNewWithLatin1Chars,
    xml_parser_open_buffer: c.GDExtensionInterfaceXmlParserOpenBuffer,
    file_access_store_buffer: c.GDExtensionInterfaceFileAccessStoreBuffer,
    file_access_get_buffer: c.GDExtensionInterfaceFileAccessGetBuffer,
    worker_thread_pool_add_native_group_task: c.GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask,
    worker_thread_pool_add_native_task: c.GDExtensionInterfaceWorkerThreadPoolAddNativeTask,
    packed_byte_array_operator_index: c.GDExtensionInterfacePackedByteArrayOperatorIndex,
    packed_byte_array_operator_index_const: c.GDExtensionInterfacePackedByteArrayOperatorIndexConst,
    packed_color_array_operator_index: c.GDExtensionInterfacePackedColorArrayOperatorIndex,
    packed_color_array_operator_index_const: c.GDExtensionInterfacePackedColorArrayOperatorIndexConst,
    packed_float32_array_operator_index: c.GDExtensionInterfacePackedFloat32ArrayOperatorIndex,
    packed_float32_array_operator_index_const: c.GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst,
    packed_float64_array_operator_index: c.GDExtensionInterfacePackedFloat64ArrayOperatorIndex,
    packed_float64_array_operator_index_const: c.GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst,
    packed_int32_array_operator_index: c.GDExtensionInterfacePackedInt32ArrayOperatorIndex,
    packed_int32_array_operator_index_const: c.GDExtensionInterfacePackedInt32ArrayOperatorIndexConst,
    packed_int64_array_operator_index: c.GDExtensionInterfacePackedInt64ArrayOperatorIndex,
    packed_int64_array_operator_index_const: c.GDExtensionInterfacePackedInt64ArrayOperatorIndexConst,
    packed_string_array_operator_index: c.GDExtensionInterfacePackedStringArrayOperatorIndex,
    packed_string_array_operator_index_const: c.GDExtensionInterfacePackedStringArrayOperatorIndexConst,
    packed_vector2_array_operator_index: c.GDExtensionInterfacePackedVector2ArrayOperatorIndex,
    packed_vector2_array_operator_index_const: c.GDExtensionInterfacePackedVector2ArrayOperatorIndexConst,
    packed_vector3_array_operator_index: c.GDExtensionInterfacePackedVector3ArrayOperatorIndex,
    packed_vector3_array_operator_index_const: c.GDExtensionInterfacePackedVector3ArrayOperatorIndexConst,
    packed_vector4_array_operator_index: c.GDExtensionInterfacePackedVector4ArrayOperatorIndex,
    packed_vector4_array_operator_index_const: c.GDExtensionInterfacePackedVector4ArrayOperatorIndexConst,
    array_operator_index: c.GDExtensionInterfaceArrayOperatorIndex,
    array_operator_index_const: c.GDExtensionInterfaceArrayOperatorIndexConst,
    array_set_typed: c.GDExtensionInterfaceArraySetTyped,
    dictionary_operator_index: c.GDExtensionInterfaceDictionaryOperatorIndex,
    dictionary_operator_index_const: c.GDExtensionInterfaceDictionaryOperatorIndexConst,
    dictionary_set_typed: c.GDExtensionInterfaceDictionarySetTyped,
    object_method_bind_call: c.GDExtensionInterfaceObjectMethodBindCall,
    object_method_bind_ptrcall: c.GDExtensionInterfaceObjectMethodBindPtrcall,
    object_destroy: c.GDExtensionInterfaceObjectDestroy,
    global_get_singleton: c.GDExtensionInterfaceGlobalGetSingleton,
    object_get_instance_binding: c.GDExtensionInterfaceObjectGetInstanceBinding,
    object_set_instance_binding: c.GDExtensionInterfaceObjectSetInstanceBinding,
    object_free_instance_binding: c.GDExtensionInterfaceObjectFreeInstanceBinding,
    object_set_instance: c.GDExtensionInterfaceObjectSetInstance,
    object_get_class_name: c.GDExtensionInterfaceObjectGetClassName,
    object_cast_to: c.GDExtensionInterfaceObjectCastTo,
    object_get_instance_from_id: c.GDExtensionInterfaceObjectGetInstanceFromId,
    object_get_instance_id: c.GDExtensionInterfaceObjectGetInstanceId,
    object_has_script_method: c.GDExtensionInterfaceObjectHasScriptMethod,
    object_call_script_method: c.GDExtensionInterfaceObjectCallScriptMethod,
    callable_custom_create2: c.GDExtensionInterfaceCallableCustomCreate2,
    callable_custom_get_userdata: c.GDExtensionInterfaceCallableCustomGetUserData,
    ref_get_object: c.GDExtensionInterfaceRefGetObject,
    ref_set_object: c.GDExtensionInterfaceRefSetObject,
    script_instance_create3: c.GDExtensionInterfaceScriptInstanceCreate3,
    placeholder_script_instance_create: c.GDExtensionInterfacePlaceHolderScriptInstanceCreate,
    placeholder_script_instance_update: c.GDExtensionInterfacePlaceHolderScriptInstanceUpdate,
    object_get_script_instance: c.GDExtensionInterfaceObjectGetScriptInstance,
    object_set_script_instance: c.GDExtensionInterfaceObjectSetScriptInstance,
    classdb_construct_object2: c.GDExtensionInterfaceClassdbConstructObject2,
    classdb_get_method_bind: c.GDExtensionInterfaceClassdbGetMethodBind,
    classdb_get_class_tag: c.GDExtensionInterfaceClassdbGetClassTag,
    classdb_register_extension_class5: c.GDExtensionInterfaceClassdbRegisterExtensionClass5,
    classdb_register_extension_class_method: c.GDExtensionInterfaceClassdbRegisterExtensionClassMethod,
    classdb_register_extension_class_virtual_method: c.GDExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod,
    classdb_register_extension_class_integer_constant: c.GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant,
    classdb_register_extension_class_property: c.GDExtensionInterfaceClassdbRegisterExtensionClassProperty,
    classdb_register_extension_class_property_indexed: c.GDExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed,
    classdb_register_extension_class_property_group: c.GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup,
    classdb_register_extension_class_property_subgroup: c.GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup,
    classdb_register_extension_class_signal: c.GDExtensionInterfaceClassdbRegisterExtensionClassSignal,
    classdb_unregister_extension_class: c.GDExtensionInterfaceClassdbUnregisterExtensionClass,
    get_library_path: c.GDExtensionInterfaceGetLibraryPath,
    editor_add_plugin: c.GDExtensionInterfaceEditorAddPlugin,
    editor_remove_plugin: c.GDExtensionInterfaceEditorRemovePlugin,
    editor_register_get_classes_used_callback: c.GDExtensionInterfaceEditorRegisterGetClassesUsedCallback,
    editor_help_load_xml_from_utf8_chars: c.GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8Chars,
    editor_help_load_xml_from_utf8_chars_and_len: c.GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen,
    image_ptrw: c.GDExtensionInterfaceImagePtrw,
    image_ptr: c.GDExtensionInterfaceImagePtr,
    register_main_loop_callbacks: c.GDExtensionInterfaceRegisterMainLoopCallbacks,

    pub fn init() error{UnableInterface}!Interfaces {
        var interfaces: Interfaces = undefined;

        interfaces.print_error = @ptrCast(get_proc_address.?("print_error"));

        if (interfaces.print_error == null) {
            interfaces.print_error.?("Unable to load GDExtension interface function", @src().fn_name, @src().file, @src().line, 0);
            return error.UnableInterface;
        }

        inline for (@typeInfo(Interfaces).@"struct".fields) |interface| {
            comptime if (std.mem.eql(u8, interface.name, "print_error"))
                continue;
            @field(interfaces, interface.name) = @ptrCast(get_proc_address.?(interface.name));
            if (@field(interfaces, interface.name) == null) {
                interfaces.print_error.?("Unable to load GDExtension interface function", @src().fn_name, @src().file, @src().line, 0);
                return error.UnableInterface;
            }
        }

        return interfaces;
    }
};
