pub const ptrdiff_t = c_long;
pub const wchar_t = c_int;
pub const int_fast8_t = i8;
pub const int_fast16_t = c_long;
pub const int_fast32_t = c_long;
pub const int_fast64_t = c_long;
pub const uint_fast8_t = u8;
pub const uint_fast16_t = c_ulong;
pub const uint_fast32_t = c_ulong;
pub const uint_fast64_t = c_ulong;
pub const char32_t = u32;
pub const char16_t = u16;
pub const GDEXTENSION_VARIANT_TYPE_NIL: c_int = 0;
pub const GDEXTENSION_VARIANT_TYPE_BOOL: c_int = 1;
pub const GDEXTENSION_VARIANT_TYPE_INT: c_int = 2;
pub const GDEXTENSION_VARIANT_TYPE_FLOAT: c_int = 3;
pub const GDEXTENSION_VARIANT_TYPE_STRING: c_int = 4;
pub const GDEXTENSION_VARIANT_TYPE_VECTOR2: c_int = 5;
pub const GDEXTENSION_VARIANT_TYPE_VECTOR2I: c_int = 6;
pub const GDEXTENSION_VARIANT_TYPE_RECT2: c_int = 7;
pub const GDEXTENSION_VARIANT_TYPE_RECT2I: c_int = 8;
pub const GDEXTENSION_VARIANT_TYPE_VECTOR3: c_int = 9;
pub const GDEXTENSION_VARIANT_TYPE_VECTOR3I: c_int = 10;
pub const GDEXTENSION_VARIANT_TYPE_TRANSFORM2D: c_int = 11;
pub const GDEXTENSION_VARIANT_TYPE_VECTOR4: c_int = 12;
pub const GDEXTENSION_VARIANT_TYPE_VECTOR4I: c_int = 13;
pub const GDEXTENSION_VARIANT_TYPE_PLANE: c_int = 14;
pub const GDEXTENSION_VARIANT_TYPE_QUATERNION: c_int = 15;
pub const GDEXTENSION_VARIANT_TYPE_AABB: c_int = 16;
pub const GDEXTENSION_VARIANT_TYPE_BASIS: c_int = 17;
pub const GDEXTENSION_VARIANT_TYPE_TRANSFORM3D: c_int = 18;
pub const GDEXTENSION_VARIANT_TYPE_PROJECTION: c_int = 19;
pub const GDEXTENSION_VARIANT_TYPE_COLOR: c_int = 20;
pub const GDEXTENSION_VARIANT_TYPE_STRING_NAME: c_int = 21;
pub const GDEXTENSION_VARIANT_TYPE_NODE_PATH: c_int = 22;
pub const GDEXTENSION_VARIANT_TYPE_RID: c_int = 23;
pub const GDEXTENSION_VARIANT_TYPE_OBJECT: c_int = 24;
pub const GDEXTENSION_VARIANT_TYPE_CALLABLE: c_int = 25;
pub const GDEXTENSION_VARIANT_TYPE_SIGNAL: c_int = 26;
pub const GDEXTENSION_VARIANT_TYPE_DICTIONARY: c_int = 27;
pub const GDEXTENSION_VARIANT_TYPE_ARRAY: c_int = 28;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_BYTE_ARRAY: c_int = 29;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_INT32_ARRAY: c_int = 30;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_INT64_ARRAY: c_int = 31;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT32_ARRAY: c_int = 32;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_FLOAT64_ARRAY: c_int = 33;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_STRING_ARRAY: c_int = 34;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR2_ARRAY: c_int = 35;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR3_ARRAY: c_int = 36;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_COLOR_ARRAY: c_int = 37;
pub const GDEXTENSION_VARIANT_TYPE_PACKED_VECTOR4_ARRAY: c_int = 38;
pub const GDEXTENSION_VARIANT_TYPE_VARIANT_MAX: c_int = 39;
pub const GDExtensionVariantType = c_uint;
pub const GDEXTENSION_VARIANT_OP_EQUAL: c_int = 0;
pub const GDEXTENSION_VARIANT_OP_NOT_EQUAL: c_int = 1;
pub const GDEXTENSION_VARIANT_OP_LESS: c_int = 2;
pub const GDEXTENSION_VARIANT_OP_LESS_EQUAL: c_int = 3;
pub const GDEXTENSION_VARIANT_OP_GREATER: c_int = 4;
pub const GDEXTENSION_VARIANT_OP_GREATER_EQUAL: c_int = 5;
pub const GDEXTENSION_VARIANT_OP_ADD: c_int = 6;
pub const GDEXTENSION_VARIANT_OP_SUBTRACT: c_int = 7;
pub const GDEXTENSION_VARIANT_OP_MULTIPLY: c_int = 8;
pub const GDEXTENSION_VARIANT_OP_DIVIDE: c_int = 9;
pub const GDEXTENSION_VARIANT_OP_NEGATE: c_int = 10;
pub const GDEXTENSION_VARIANT_OP_POSITIVE: c_int = 11;
pub const GDEXTENSION_VARIANT_OP_MODULE: c_int = 12;
pub const GDEXTENSION_VARIANT_OP_POWER: c_int = 13;
pub const GDEXTENSION_VARIANT_OP_SHIFT_LEFT: c_int = 14;
pub const GDEXTENSION_VARIANT_OP_SHIFT_RIGHT: c_int = 15;
pub const GDEXTENSION_VARIANT_OP_BIT_AND: c_int = 16;
pub const GDEXTENSION_VARIANT_OP_BIT_OR: c_int = 17;
pub const GDEXTENSION_VARIANT_OP_BIT_XOR: c_int = 18;
pub const GDEXTENSION_VARIANT_OP_BIT_NEGATE: c_int = 19;
pub const GDEXTENSION_VARIANT_OP_AND: c_int = 20;
pub const GDEXTENSION_VARIANT_OP_OR: c_int = 21;
pub const GDEXTENSION_VARIANT_OP_XOR: c_int = 22;
pub const GDEXTENSION_VARIANT_OP_NOT: c_int = 23;
pub const GDEXTENSION_VARIANT_OP_IN: c_int = 24;
pub const GDEXTENSION_VARIANT_OP_MAX: c_int = 25;
pub const GDExtensionVariantOperator = c_uint;
pub const GDExtensionVariantPtr = ?*anyopaque;
pub const GDExtensionConstVariantPtr = ?*const anyopaque;
pub const GDExtensionUninitializedVariantPtr = ?*anyopaque;
pub const GDExtensionStringNamePtr = ?*anyopaque;
pub const GDExtensionConstStringNamePtr = ?*const anyopaque;
pub const GDExtensionUninitializedStringNamePtr = ?*anyopaque;
pub const GDExtensionStringPtr = ?*anyopaque;
pub const GDExtensionConstStringPtr = ?*const anyopaque;
pub const GDExtensionUninitializedStringPtr = ?*anyopaque;
pub const GDExtensionObjectPtr = ?*anyopaque;
pub const GDExtensionConstObjectPtr = ?*const anyopaque;
pub const GDExtensionUninitializedObjectPtr = ?*anyopaque;
pub const GDExtensionTypePtr = ?*anyopaque;
pub const GDExtensionConstTypePtr = ?*const anyopaque;
pub const GDExtensionUninitializedTypePtr = ?*anyopaque;
pub const GDExtensionMethodBindPtr = ?*const anyopaque;
pub const GDExtensionInt = i64;
pub const GDExtensionBool = u8;
pub const GDObjectInstanceID = u64;
pub const GDExtensionRefPtr = ?*anyopaque;
pub const GDExtensionConstRefPtr = ?*const anyopaque;
pub const GDEXTENSION_CALL_OK: c_int = 0;
pub const GDEXTENSION_CALL_ERROR_INVALID_METHOD: c_int = 1;
pub const GDEXTENSION_CALL_ERROR_INVALID_ARGUMENT: c_int = 2;
pub const GDEXTENSION_CALL_ERROR_TOO_MANY_ARGUMENTS: c_int = 3;
pub const GDEXTENSION_CALL_ERROR_TOO_FEW_ARGUMENTS: c_int = 4;
pub const GDEXTENSION_CALL_ERROR_INSTANCE_IS_NULL: c_int = 5;
pub const GDEXTENSION_CALL_ERROR_METHOD_NOT_CONST: c_int = 6;
pub const GDExtensionCallErrorType = c_uint;
pub const GDExtensionCallError = extern struct {
    @"error": GDExtensionCallErrorType = @import("std").mem.zeroes(GDExtensionCallErrorType),
    argument: i32 = @import("std").mem.zeroes(i32),
    expected: i32 = @import("std").mem.zeroes(i32),
};
pub const GDExtensionVariantFromTypeConstructorFunc = ?*const fn (GDExtensionUninitializedVariantPtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionTypeFromVariantConstructorFunc = ?*const fn (GDExtensionUninitializedTypePtr, GDExtensionVariantPtr) callconv(.c) void;
pub const GDExtensionVariantGetInternalPtrFunc = ?*const fn (GDExtensionVariantPtr) callconv(.c) ?*anyopaque;
pub const GDExtensionPtrOperatorEvaluator = ?*const fn (GDExtensionConstTypePtr, GDExtensionConstTypePtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionPtrBuiltInMethod = ?*const fn (GDExtensionTypePtr, [*c]const GDExtensionConstTypePtr, GDExtensionTypePtr, c_int) callconv(.c) void;
pub const GDExtensionPtrConstructor = ?*const fn (GDExtensionUninitializedTypePtr, [*c]const GDExtensionConstTypePtr) callconv(.c) void;
pub const GDExtensionPtrDestructor = ?*const fn (GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionPtrSetter = ?*const fn (GDExtensionTypePtr, GDExtensionConstTypePtr) callconv(.c) void;
pub const GDExtensionPtrGetter = ?*const fn (GDExtensionConstTypePtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionPtrIndexedSetter = ?*const fn (GDExtensionTypePtr, GDExtensionInt, GDExtensionConstTypePtr) callconv(.c) void;
pub const GDExtensionPtrIndexedGetter = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionPtrKeyedSetter = ?*const fn (GDExtensionTypePtr, GDExtensionConstTypePtr, GDExtensionConstTypePtr) callconv(.c) void;
pub const GDExtensionPtrKeyedGetter = ?*const fn (GDExtensionConstTypePtr, GDExtensionConstTypePtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionPtrKeyedChecker = ?*const fn (GDExtensionConstVariantPtr, GDExtensionConstVariantPtr) callconv(.c) u32;
pub const GDExtensionPtrUtilityFunction = ?*const fn (GDExtensionTypePtr, [*c]const GDExtensionConstTypePtr, c_int) callconv(.c) void;
pub const GDExtensionClassConstructor = ?*const fn (...) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionInstanceBindingCreateCallback = ?*const fn (?*anyopaque, ?*anyopaque) callconv(.c) ?*anyopaque;
pub const GDExtensionInstanceBindingFreeCallback = ?*const fn (?*anyopaque, ?*anyopaque, ?*anyopaque) callconv(.c) void;
pub const GDExtensionInstanceBindingReferenceCallback = ?*const fn (?*anyopaque, ?*anyopaque, GDExtensionBool) callconv(.c) GDExtensionBool;
pub const GDExtensionInstanceBindingCallbacks = extern struct {
    create_callback: GDExtensionInstanceBindingCreateCallback = @import("std").mem.zeroes(GDExtensionInstanceBindingCreateCallback),
    free_callback: GDExtensionInstanceBindingFreeCallback = @import("std").mem.zeroes(GDExtensionInstanceBindingFreeCallback),
    reference_callback: GDExtensionInstanceBindingReferenceCallback = @import("std").mem.zeroes(GDExtensionInstanceBindingReferenceCallback),
};
pub const GDExtensionClassInstancePtr = ?*anyopaque;
pub const GDExtensionClassSet = ?*const fn (GDExtensionClassInstancePtr, GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionClassGet = ?*const fn (GDExtensionClassInstancePtr, GDExtensionConstStringNamePtr, GDExtensionVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionClassGetRID = ?*const fn (GDExtensionClassInstancePtr) callconv(.c) u64;
pub const GDExtensionPropertyInfo = extern struct {
    type: GDExtensionVariantType = @import("std").mem.zeroes(GDExtensionVariantType),
    name: GDExtensionStringNamePtr = @import("std").mem.zeroes(GDExtensionStringNamePtr),
    class_name: GDExtensionStringNamePtr = @import("std").mem.zeroes(GDExtensionStringNamePtr),
    hint: u32 = @import("std").mem.zeroes(u32),
    hint_string: GDExtensionStringPtr = @import("std").mem.zeroes(GDExtensionStringPtr),
    usage: u32 = @import("std").mem.zeroes(u32),
};
pub const GDExtensionMethodInfo = extern struct {
    name: GDExtensionStringNamePtr = @import("std").mem.zeroes(GDExtensionStringNamePtr),
    return_value: GDExtensionPropertyInfo = @import("std").mem.zeroes(GDExtensionPropertyInfo),
    flags: u32 = @import("std").mem.zeroes(u32),
    id: i32 = @import("std").mem.zeroes(i32),
    argument_count: u32 = @import("std").mem.zeroes(u32),
    arguments: [*c]GDExtensionPropertyInfo = @import("std").mem.zeroes([*c]GDExtensionPropertyInfo),
    default_argument_count: u32 = @import("std").mem.zeroes(u32),
    default_arguments: [*c]GDExtensionVariantPtr = @import("std").mem.zeroes([*c]GDExtensionVariantPtr),
};
pub const GDExtensionClassGetPropertyList = ?*const fn (GDExtensionClassInstancePtr, [*c]u32) callconv(.c) [*c]const GDExtensionPropertyInfo;
pub const GDExtensionClassFreePropertyList = ?*const fn (GDExtensionClassInstancePtr, [*c]const GDExtensionPropertyInfo) callconv(.c) void;
pub const GDExtensionClassFreePropertyList2 = ?*const fn (GDExtensionClassInstancePtr, [*c]const GDExtensionPropertyInfo, u32) callconv(.c) void;
pub const GDExtensionClassPropertyCanRevert = ?*const fn (GDExtensionClassInstancePtr, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionBool;
pub const GDExtensionClassPropertyGetRevert = ?*const fn (GDExtensionClassInstancePtr, GDExtensionConstStringNamePtr, GDExtensionVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionClassValidateProperty = ?*const fn (GDExtensionClassInstancePtr, [*c]GDExtensionPropertyInfo) callconv(.c) GDExtensionBool;
pub const GDExtensionClassNotification = ?*const fn (GDExtensionClassInstancePtr, i32) callconv(.c) void;
pub const GDExtensionClassNotification2 = ?*const fn (GDExtensionClassInstancePtr, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionClassToString = ?*const fn (GDExtensionClassInstancePtr, [*c]GDExtensionBool, GDExtensionStringPtr) callconv(.c) void;
pub const GDExtensionClassReference = ?*const fn (GDExtensionClassInstancePtr) callconv(.c) void;
pub const GDExtensionClassUnreference = ?*const fn (GDExtensionClassInstancePtr) callconv(.c) void;
pub const GDExtensionClassCallVirtual = ?*const fn (GDExtensionClassInstancePtr, [*c]const GDExtensionConstTypePtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionClassCreateInstance = ?*const fn (?*anyopaque) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionClassCreateInstance2 = ?*const fn (?*anyopaque, GDExtensionBool) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionClassFreeInstance = ?*const fn (?*anyopaque, GDExtensionClassInstancePtr) callconv(.c) void;
pub const GDExtensionClassRecreateInstance = ?*const fn (?*anyopaque, GDExtensionObjectPtr) callconv(.c) GDExtensionClassInstancePtr;
pub const GDExtensionClassGetVirtual = ?*const fn (?*anyopaque, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionClassCallVirtual;
pub const GDExtensionClassGetVirtual2 = ?*const fn (?*anyopaque, GDExtensionConstStringNamePtr, u32) callconv(.c) GDExtensionClassCallVirtual;
pub const GDExtensionClassGetVirtualCallData = ?*const fn (?*anyopaque, GDExtensionConstStringNamePtr) callconv(.c) ?*anyopaque;
pub const GDExtensionClassGetVirtualCallData2 = ?*const fn (?*anyopaque, GDExtensionConstStringNamePtr, u32) callconv(.c) ?*anyopaque;
pub const GDExtensionClassCallVirtualWithData = ?*const fn (GDExtensionClassInstancePtr, GDExtensionConstStringNamePtr, ?*anyopaque, [*c]const GDExtensionConstTypePtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionClassCreationInfo = extern struct {
    is_virtual: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_abstract: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    set_func: GDExtensionClassSet = @import("std").mem.zeroes(GDExtensionClassSet),
    get_func: GDExtensionClassGet = @import("std").mem.zeroes(GDExtensionClassGet),
    get_property_list_func: GDExtensionClassGetPropertyList = @import("std").mem.zeroes(GDExtensionClassGetPropertyList),
    free_property_list_func: GDExtensionClassFreePropertyList = @import("std").mem.zeroes(GDExtensionClassFreePropertyList),
    property_can_revert_func: GDExtensionClassPropertyCanRevert = @import("std").mem.zeroes(GDExtensionClassPropertyCanRevert),
    property_get_revert_func: GDExtensionClassPropertyGetRevert = @import("std").mem.zeroes(GDExtensionClassPropertyGetRevert),
    notification_func: GDExtensionClassNotification = @import("std").mem.zeroes(GDExtensionClassNotification),
    to_string_func: GDExtensionClassToString = @import("std").mem.zeroes(GDExtensionClassToString),
    reference_func: GDExtensionClassReference = @import("std").mem.zeroes(GDExtensionClassReference),
    unreference_func: GDExtensionClassUnreference = @import("std").mem.zeroes(GDExtensionClassUnreference),
    create_instance_func: GDExtensionClassCreateInstance = @import("std").mem.zeroes(GDExtensionClassCreateInstance),
    free_instance_func: GDExtensionClassFreeInstance = @import("std").mem.zeroes(GDExtensionClassFreeInstance),
    get_virtual_func: GDExtensionClassGetVirtual = @import("std").mem.zeroes(GDExtensionClassGetVirtual),
    get_rid_func: GDExtensionClassGetRID = @import("std").mem.zeroes(GDExtensionClassGetRID),
    class_userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
};
pub const GDExtensionClassCreationInfo2 = extern struct {
    is_virtual: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_abstract: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_exposed: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    set_func: GDExtensionClassSet = @import("std").mem.zeroes(GDExtensionClassSet),
    get_func: GDExtensionClassGet = @import("std").mem.zeroes(GDExtensionClassGet),
    get_property_list_func: GDExtensionClassGetPropertyList = @import("std").mem.zeroes(GDExtensionClassGetPropertyList),
    free_property_list_func: GDExtensionClassFreePropertyList = @import("std").mem.zeroes(GDExtensionClassFreePropertyList),
    property_can_revert_func: GDExtensionClassPropertyCanRevert = @import("std").mem.zeroes(GDExtensionClassPropertyCanRevert),
    property_get_revert_func: GDExtensionClassPropertyGetRevert = @import("std").mem.zeroes(GDExtensionClassPropertyGetRevert),
    validate_property_func: GDExtensionClassValidateProperty = @import("std").mem.zeroes(GDExtensionClassValidateProperty),
    notification_func: GDExtensionClassNotification2 = @import("std").mem.zeroes(GDExtensionClassNotification2),
    to_string_func: GDExtensionClassToString = @import("std").mem.zeroes(GDExtensionClassToString),
    reference_func: GDExtensionClassReference = @import("std").mem.zeroes(GDExtensionClassReference),
    unreference_func: GDExtensionClassUnreference = @import("std").mem.zeroes(GDExtensionClassUnreference),
    create_instance_func: GDExtensionClassCreateInstance = @import("std").mem.zeroes(GDExtensionClassCreateInstance),
    free_instance_func: GDExtensionClassFreeInstance = @import("std").mem.zeroes(GDExtensionClassFreeInstance),
    recreate_instance_func: GDExtensionClassRecreateInstance = @import("std").mem.zeroes(GDExtensionClassRecreateInstance),
    get_virtual_func: GDExtensionClassGetVirtual = @import("std").mem.zeroes(GDExtensionClassGetVirtual),
    get_virtual_call_data_func: GDExtensionClassGetVirtualCallData = @import("std").mem.zeroes(GDExtensionClassGetVirtualCallData),
    call_virtual_with_data_func: GDExtensionClassCallVirtualWithData = @import("std").mem.zeroes(GDExtensionClassCallVirtualWithData),
    get_rid_func: GDExtensionClassGetRID = @import("std").mem.zeroes(GDExtensionClassGetRID),
    class_userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
};
pub const GDExtensionClassCreationInfo3 = extern struct {
    is_virtual: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_abstract: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_exposed: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_runtime: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    set_func: GDExtensionClassSet = @import("std").mem.zeroes(GDExtensionClassSet),
    get_func: GDExtensionClassGet = @import("std").mem.zeroes(GDExtensionClassGet),
    get_property_list_func: GDExtensionClassGetPropertyList = @import("std").mem.zeroes(GDExtensionClassGetPropertyList),
    free_property_list_func: GDExtensionClassFreePropertyList2 = @import("std").mem.zeroes(GDExtensionClassFreePropertyList2),
    property_can_revert_func: GDExtensionClassPropertyCanRevert = @import("std").mem.zeroes(GDExtensionClassPropertyCanRevert),
    property_get_revert_func: GDExtensionClassPropertyGetRevert = @import("std").mem.zeroes(GDExtensionClassPropertyGetRevert),
    validate_property_func: GDExtensionClassValidateProperty = @import("std").mem.zeroes(GDExtensionClassValidateProperty),
    notification_func: GDExtensionClassNotification2 = @import("std").mem.zeroes(GDExtensionClassNotification2),
    to_string_func: GDExtensionClassToString = @import("std").mem.zeroes(GDExtensionClassToString),
    reference_func: GDExtensionClassReference = @import("std").mem.zeroes(GDExtensionClassReference),
    unreference_func: GDExtensionClassUnreference = @import("std").mem.zeroes(GDExtensionClassUnreference),
    create_instance_func: GDExtensionClassCreateInstance = @import("std").mem.zeroes(GDExtensionClassCreateInstance),
    free_instance_func: GDExtensionClassFreeInstance = @import("std").mem.zeroes(GDExtensionClassFreeInstance),
    recreate_instance_func: GDExtensionClassRecreateInstance = @import("std").mem.zeroes(GDExtensionClassRecreateInstance),
    get_virtual_func: GDExtensionClassGetVirtual = @import("std").mem.zeroes(GDExtensionClassGetVirtual),
    get_virtual_call_data_func: GDExtensionClassGetVirtualCallData = @import("std").mem.zeroes(GDExtensionClassGetVirtualCallData),
    call_virtual_with_data_func: GDExtensionClassCallVirtualWithData = @import("std").mem.zeroes(GDExtensionClassCallVirtualWithData),
    get_rid_func: GDExtensionClassGetRID = @import("std").mem.zeroes(GDExtensionClassGetRID),
    class_userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
};
pub const GDExtensionClassCreationInfo4 = extern struct {
    is_virtual: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_abstract: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_exposed: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    is_runtime: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    icon_path: GDExtensionConstStringPtr = @import("std").mem.zeroes(GDExtensionConstStringPtr),
    set_func: GDExtensionClassSet = @import("std").mem.zeroes(GDExtensionClassSet),
    get_func: GDExtensionClassGet = @import("std").mem.zeroes(GDExtensionClassGet),
    get_property_list_func: GDExtensionClassGetPropertyList = @import("std").mem.zeroes(GDExtensionClassGetPropertyList),
    free_property_list_func: GDExtensionClassFreePropertyList2 = @import("std").mem.zeroes(GDExtensionClassFreePropertyList2),
    property_can_revert_func: GDExtensionClassPropertyCanRevert = @import("std").mem.zeroes(GDExtensionClassPropertyCanRevert),
    property_get_revert_func: GDExtensionClassPropertyGetRevert = @import("std").mem.zeroes(GDExtensionClassPropertyGetRevert),
    validate_property_func: GDExtensionClassValidateProperty = @import("std").mem.zeroes(GDExtensionClassValidateProperty),
    notification_func: GDExtensionClassNotification2 = @import("std").mem.zeroes(GDExtensionClassNotification2),
    to_string_func: GDExtensionClassToString = @import("std").mem.zeroes(GDExtensionClassToString),
    reference_func: GDExtensionClassReference = @import("std").mem.zeroes(GDExtensionClassReference),
    unreference_func: GDExtensionClassUnreference = @import("std").mem.zeroes(GDExtensionClassUnreference),
    create_instance_func: GDExtensionClassCreateInstance2 = @import("std").mem.zeroes(GDExtensionClassCreateInstance2),
    free_instance_func: GDExtensionClassFreeInstance = @import("std").mem.zeroes(GDExtensionClassFreeInstance),
    recreate_instance_func: GDExtensionClassRecreateInstance = @import("std").mem.zeroes(GDExtensionClassRecreateInstance),
    get_virtual_func: GDExtensionClassGetVirtual2 = @import("std").mem.zeroes(GDExtensionClassGetVirtual2),
    get_virtual_call_data_func: GDExtensionClassGetVirtualCallData2 = @import("std").mem.zeroes(GDExtensionClassGetVirtualCallData2),
    call_virtual_with_data_func: GDExtensionClassCallVirtualWithData = @import("std").mem.zeroes(GDExtensionClassCallVirtualWithData),
    class_userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
};
pub const GDExtensionClassCreationInfo5 = GDExtensionClassCreationInfo4;
pub const GDExtensionClassLibraryPtr = ?*anyopaque;
pub const GDExtensionEditorGetClassesUsedCallback = ?*const fn (GDExtensionTypePtr) callconv(.c) void;
pub const GDEXTENSION_METHOD_FLAG_NORMAL: c_int = 1;
pub const GDEXTENSION_METHOD_FLAG_EDITOR: c_int = 2;
pub const GDEXTENSION_METHOD_FLAG_CONST: c_int = 4;
pub const GDEXTENSION_METHOD_FLAG_VIRTUAL: c_int = 8;
pub const GDEXTENSION_METHOD_FLAG_VARARG: c_int = 16;
pub const GDEXTENSION_METHOD_FLAG_STATIC: c_int = 32;
pub const GDEXTENSION_METHOD_FLAGS_DEFAULT: c_int = 1;
pub const GDExtensionClassMethodFlags = c_uint;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_NONE: c_int = 0;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT8: c_int = 1;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT16: c_int = 2;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT32: c_int = 3;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_INT64: c_int = 4;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT8: c_int = 5;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT16: c_int = 6;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT32: c_int = 7;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_UINT64: c_int = 8;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_FLOAT: c_int = 9;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_REAL_IS_DOUBLE: c_int = 10;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR16: c_int = 11;
pub const GDEXTENSION_METHOD_ARGUMENT_METADATA_INT_IS_CHAR32: c_int = 12;
pub const GDExtensionClassMethodArgumentMetadata = c_uint;
pub const GDExtensionClassMethodCall = ?*const fn (?*anyopaque, GDExtensionClassInstancePtr, [*c]const GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionVariantPtr, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionClassMethodValidatedCall = ?*const fn (?*anyopaque, GDExtensionClassInstancePtr, [*c]const GDExtensionConstVariantPtr, GDExtensionVariantPtr) callconv(.c) void;
pub const GDExtensionClassMethodPtrCall = ?*const fn (?*anyopaque, GDExtensionClassInstancePtr, [*c]const GDExtensionConstTypePtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionClassMethodInfo = extern struct {
    name: GDExtensionStringNamePtr = @import("std").mem.zeroes(GDExtensionStringNamePtr),
    method_userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
    call_func: GDExtensionClassMethodCall = @import("std").mem.zeroes(GDExtensionClassMethodCall),
    ptrcall_func: GDExtensionClassMethodPtrCall = @import("std").mem.zeroes(GDExtensionClassMethodPtrCall),
    method_flags: u32 = @import("std").mem.zeroes(u32),
    has_return_value: GDExtensionBool = @import("std").mem.zeroes(GDExtensionBool),
    return_value_info: [*c]GDExtensionPropertyInfo = @import("std").mem.zeroes([*c]GDExtensionPropertyInfo),
    return_value_metadata: GDExtensionClassMethodArgumentMetadata = @import("std").mem.zeroes(GDExtensionClassMethodArgumentMetadata),
    argument_count: u32 = @import("std").mem.zeroes(u32),
    arguments_info: [*c]GDExtensionPropertyInfo = @import("std").mem.zeroes([*c]GDExtensionPropertyInfo),
    arguments_metadata: [*c]GDExtensionClassMethodArgumentMetadata = @import("std").mem.zeroes([*c]GDExtensionClassMethodArgumentMetadata),
    default_argument_count: u32 = @import("std").mem.zeroes(u32),
    default_arguments: [*c]GDExtensionVariantPtr = @import("std").mem.zeroes([*c]GDExtensionVariantPtr),
};
pub const GDExtensionClassVirtualMethodInfo = extern struct {
    name: GDExtensionStringNamePtr = @import("std").mem.zeroes(GDExtensionStringNamePtr),
    method_flags: u32 = @import("std").mem.zeroes(u32),
    return_value: GDExtensionPropertyInfo = @import("std").mem.zeroes(GDExtensionPropertyInfo),
    return_value_metadata: GDExtensionClassMethodArgumentMetadata = @import("std").mem.zeroes(GDExtensionClassMethodArgumentMetadata),
    argument_count: u32 = @import("std").mem.zeroes(u32),
    arguments: [*c]GDExtensionPropertyInfo = @import("std").mem.zeroes([*c]GDExtensionPropertyInfo),
    arguments_metadata: [*c]GDExtensionClassMethodArgumentMetadata = @import("std").mem.zeroes([*c]GDExtensionClassMethodArgumentMetadata),
};
pub const GDExtensionCallableCustomCall = ?*const fn (?*anyopaque, [*c]const GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionVariantPtr, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionCallableCustomIsValid = ?*const fn (?*anyopaque) callconv(.c) GDExtensionBool;
pub const GDExtensionCallableCustomFree = ?*const fn (?*anyopaque) callconv(.c) void;
pub const GDExtensionCallableCustomHash = ?*const fn (?*anyopaque) callconv(.c) u32;
pub const GDExtensionCallableCustomEqual = ?*const fn (?*anyopaque, ?*anyopaque) callconv(.c) GDExtensionBool;
pub const GDExtensionCallableCustomLessThan = ?*const fn (?*anyopaque, ?*anyopaque) callconv(.c) GDExtensionBool;
pub const GDExtensionCallableCustomToString = ?*const fn (?*anyopaque, [*c]GDExtensionBool, GDExtensionStringPtr) callconv(.c) void;
pub const GDExtensionCallableCustomGetArgumentCount = ?*const fn (?*anyopaque, [*c]GDExtensionBool) callconv(.c) GDExtensionInt;
pub const GDExtensionCallableCustomInfo = extern struct {
    callable_userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
    token: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
    object_id: GDObjectInstanceID = @import("std").mem.zeroes(GDObjectInstanceID),
    call_func: GDExtensionCallableCustomCall = @import("std").mem.zeroes(GDExtensionCallableCustomCall),
    is_valid_func: GDExtensionCallableCustomIsValid = @import("std").mem.zeroes(GDExtensionCallableCustomIsValid),
    free_func: GDExtensionCallableCustomFree = @import("std").mem.zeroes(GDExtensionCallableCustomFree),
    hash_func: GDExtensionCallableCustomHash = @import("std").mem.zeroes(GDExtensionCallableCustomHash),
    equal_func: GDExtensionCallableCustomEqual = @import("std").mem.zeroes(GDExtensionCallableCustomEqual),
    less_than_func: GDExtensionCallableCustomLessThan = @import("std").mem.zeroes(GDExtensionCallableCustomLessThan),
    to_string_func: GDExtensionCallableCustomToString = @import("std").mem.zeroes(GDExtensionCallableCustomToString),
};
pub const GDExtensionCallableCustomInfo2 = extern struct {
    callable_userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
    token: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
    object_id: GDObjectInstanceID = @import("std").mem.zeroes(GDObjectInstanceID),
    call_func: GDExtensionCallableCustomCall = @import("std").mem.zeroes(GDExtensionCallableCustomCall),
    is_valid_func: GDExtensionCallableCustomIsValid = @import("std").mem.zeroes(GDExtensionCallableCustomIsValid),
    free_func: GDExtensionCallableCustomFree = @import("std").mem.zeroes(GDExtensionCallableCustomFree),
    hash_func: GDExtensionCallableCustomHash = @import("std").mem.zeroes(GDExtensionCallableCustomHash),
    equal_func: GDExtensionCallableCustomEqual = @import("std").mem.zeroes(GDExtensionCallableCustomEqual),
    less_than_func: GDExtensionCallableCustomLessThan = @import("std").mem.zeroes(GDExtensionCallableCustomLessThan),
    to_string_func: GDExtensionCallableCustomToString = @import("std").mem.zeroes(GDExtensionCallableCustomToString),
    get_argument_count_func: GDExtensionCallableCustomGetArgumentCount = @import("std").mem.zeroes(GDExtensionCallableCustomGetArgumentCount),
};
pub const GDExtensionScriptInstanceDataPtr = ?*anyopaque;
pub const GDExtensionScriptInstanceSet = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstanceGet = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr, GDExtensionVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstanceGetPropertyList = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]u32) callconv(.c) [*c]const GDExtensionPropertyInfo;
pub const GDExtensionScriptInstanceFreePropertyList = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]const GDExtensionPropertyInfo) callconv(.c) void;
pub const GDExtensionScriptInstanceFreePropertyList2 = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]const GDExtensionPropertyInfo, u32) callconv(.c) void;
pub const GDExtensionScriptInstanceGetClassCategory = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]GDExtensionPropertyInfo) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstanceGetPropertyType = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr, [*c]GDExtensionBool) callconv(.c) GDExtensionVariantType;
pub const GDExtensionScriptInstanceValidateProperty = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]GDExtensionPropertyInfo) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstancePropertyCanRevert = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstancePropertyGetRevert = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr, GDExtensionVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstanceGetOwner = ?*const fn (GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionScriptInstancePropertyStateAdd = ?*const fn (GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr, ?*anyopaque) callconv(.c) void;
pub const GDExtensionScriptInstanceGetPropertyState = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionScriptInstancePropertyStateAdd, ?*anyopaque) callconv(.c) void;
pub const GDExtensionScriptInstanceGetMethodList = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]u32) callconv(.c) [*c]const GDExtensionMethodInfo;
pub const GDExtensionScriptInstanceFreeMethodList = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]const GDExtensionMethodInfo) callconv(.c) void;
pub const GDExtensionScriptInstanceFreeMethodList2 = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]const GDExtensionMethodInfo, u32) callconv(.c) void;
pub const GDExtensionScriptInstanceHasMethod = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstanceGetMethodArgumentCount = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr, [*c]GDExtensionBool) callconv(.c) GDExtensionInt;
pub const GDExtensionScriptInstanceCall = ?*const fn (GDExtensionScriptInstanceDataPtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionVariantPtr, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionScriptInstanceNotification = ?*const fn (GDExtensionScriptInstanceDataPtr, i32) callconv(.c) void;
pub const GDExtensionScriptInstanceNotification2 = ?*const fn (GDExtensionScriptInstanceDataPtr, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionScriptInstanceToString = ?*const fn (GDExtensionScriptInstanceDataPtr, [*c]GDExtensionBool, GDExtensionStringPtr) callconv(.c) void;
pub const GDExtensionScriptInstanceRefCountIncremented = ?*const fn (GDExtensionScriptInstanceDataPtr) callconv(.c) void;
pub const GDExtensionScriptInstanceRefCountDecremented = ?*const fn (GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptInstanceGetScript = ?*const fn (GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionScriptInstanceIsPlaceholder = ?*const fn (GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionScriptLanguagePtr = ?*anyopaque;
pub const GDExtensionScriptInstanceGetLanguage = ?*const fn (GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionScriptLanguagePtr;
pub const GDExtensionScriptInstanceFree = ?*const fn (GDExtensionScriptInstanceDataPtr) callconv(.c) void;
pub const GDExtensionScriptInstancePtr = ?*anyopaque;
pub const GDExtensionScriptInstanceInfo = extern struct {
    set_func: GDExtensionScriptInstanceSet = @import("std").mem.zeroes(GDExtensionScriptInstanceSet),
    get_func: GDExtensionScriptInstanceGet = @import("std").mem.zeroes(GDExtensionScriptInstanceGet),
    get_property_list_func: GDExtensionScriptInstanceGetPropertyList = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyList),
    free_property_list_func: GDExtensionScriptInstanceFreePropertyList = @import("std").mem.zeroes(GDExtensionScriptInstanceFreePropertyList),
    property_can_revert_func: GDExtensionScriptInstancePropertyCanRevert = @import("std").mem.zeroes(GDExtensionScriptInstancePropertyCanRevert),
    property_get_revert_func: GDExtensionScriptInstancePropertyGetRevert = @import("std").mem.zeroes(GDExtensionScriptInstancePropertyGetRevert),
    get_owner_func: GDExtensionScriptInstanceGetOwner = @import("std").mem.zeroes(GDExtensionScriptInstanceGetOwner),
    get_property_state_func: GDExtensionScriptInstanceGetPropertyState = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyState),
    get_method_list_func: GDExtensionScriptInstanceGetMethodList = @import("std").mem.zeroes(GDExtensionScriptInstanceGetMethodList),
    free_method_list_func: GDExtensionScriptInstanceFreeMethodList = @import("std").mem.zeroes(GDExtensionScriptInstanceFreeMethodList),
    get_property_type_func: GDExtensionScriptInstanceGetPropertyType = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyType),
    has_method_func: GDExtensionScriptInstanceHasMethod = @import("std").mem.zeroes(GDExtensionScriptInstanceHasMethod),
    call_func: GDExtensionScriptInstanceCall = @import("std").mem.zeroes(GDExtensionScriptInstanceCall),
    notification_func: GDExtensionScriptInstanceNotification = @import("std").mem.zeroes(GDExtensionScriptInstanceNotification),
    to_string_func: GDExtensionScriptInstanceToString = @import("std").mem.zeroes(GDExtensionScriptInstanceToString),
    refcount_incremented_func: GDExtensionScriptInstanceRefCountIncremented = @import("std").mem.zeroes(GDExtensionScriptInstanceRefCountIncremented),
    refcount_decremented_func: GDExtensionScriptInstanceRefCountDecremented = @import("std").mem.zeroes(GDExtensionScriptInstanceRefCountDecremented),
    get_script_func: GDExtensionScriptInstanceGetScript = @import("std").mem.zeroes(GDExtensionScriptInstanceGetScript),
    is_placeholder_func: GDExtensionScriptInstanceIsPlaceholder = @import("std").mem.zeroes(GDExtensionScriptInstanceIsPlaceholder),
    set_fallback_func: GDExtensionScriptInstanceSet = @import("std").mem.zeroes(GDExtensionScriptInstanceSet),
    get_fallback_func: GDExtensionScriptInstanceGet = @import("std").mem.zeroes(GDExtensionScriptInstanceGet),
    get_language_func: GDExtensionScriptInstanceGetLanguage = @import("std").mem.zeroes(GDExtensionScriptInstanceGetLanguage),
    free_func: GDExtensionScriptInstanceFree = @import("std").mem.zeroes(GDExtensionScriptInstanceFree),
};
pub const GDExtensionScriptInstanceInfo2 = extern struct {
    set_func: GDExtensionScriptInstanceSet = @import("std").mem.zeroes(GDExtensionScriptInstanceSet),
    get_func: GDExtensionScriptInstanceGet = @import("std").mem.zeroes(GDExtensionScriptInstanceGet),
    get_property_list_func: GDExtensionScriptInstanceGetPropertyList = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyList),
    free_property_list_func: GDExtensionScriptInstanceFreePropertyList = @import("std").mem.zeroes(GDExtensionScriptInstanceFreePropertyList),
    get_class_category_func: GDExtensionScriptInstanceGetClassCategory = @import("std").mem.zeroes(GDExtensionScriptInstanceGetClassCategory),
    property_can_revert_func: GDExtensionScriptInstancePropertyCanRevert = @import("std").mem.zeroes(GDExtensionScriptInstancePropertyCanRevert),
    property_get_revert_func: GDExtensionScriptInstancePropertyGetRevert = @import("std").mem.zeroes(GDExtensionScriptInstancePropertyGetRevert),
    get_owner_func: GDExtensionScriptInstanceGetOwner = @import("std").mem.zeroes(GDExtensionScriptInstanceGetOwner),
    get_property_state_func: GDExtensionScriptInstanceGetPropertyState = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyState),
    get_method_list_func: GDExtensionScriptInstanceGetMethodList = @import("std").mem.zeroes(GDExtensionScriptInstanceGetMethodList),
    free_method_list_func: GDExtensionScriptInstanceFreeMethodList = @import("std").mem.zeroes(GDExtensionScriptInstanceFreeMethodList),
    get_property_type_func: GDExtensionScriptInstanceGetPropertyType = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyType),
    validate_property_func: GDExtensionScriptInstanceValidateProperty = @import("std").mem.zeroes(GDExtensionScriptInstanceValidateProperty),
    has_method_func: GDExtensionScriptInstanceHasMethod = @import("std").mem.zeroes(GDExtensionScriptInstanceHasMethod),
    call_func: GDExtensionScriptInstanceCall = @import("std").mem.zeroes(GDExtensionScriptInstanceCall),
    notification_func: GDExtensionScriptInstanceNotification2 = @import("std").mem.zeroes(GDExtensionScriptInstanceNotification2),
    to_string_func: GDExtensionScriptInstanceToString = @import("std").mem.zeroes(GDExtensionScriptInstanceToString),
    refcount_incremented_func: GDExtensionScriptInstanceRefCountIncremented = @import("std").mem.zeroes(GDExtensionScriptInstanceRefCountIncremented),
    refcount_decremented_func: GDExtensionScriptInstanceRefCountDecremented = @import("std").mem.zeroes(GDExtensionScriptInstanceRefCountDecremented),
    get_script_func: GDExtensionScriptInstanceGetScript = @import("std").mem.zeroes(GDExtensionScriptInstanceGetScript),
    is_placeholder_func: GDExtensionScriptInstanceIsPlaceholder = @import("std").mem.zeroes(GDExtensionScriptInstanceIsPlaceholder),
    set_fallback_func: GDExtensionScriptInstanceSet = @import("std").mem.zeroes(GDExtensionScriptInstanceSet),
    get_fallback_func: GDExtensionScriptInstanceGet = @import("std").mem.zeroes(GDExtensionScriptInstanceGet),
    get_language_func: GDExtensionScriptInstanceGetLanguage = @import("std").mem.zeroes(GDExtensionScriptInstanceGetLanguage),
    free_func: GDExtensionScriptInstanceFree = @import("std").mem.zeroes(GDExtensionScriptInstanceFree),
};
pub const GDExtensionScriptInstanceInfo3 = extern struct {
    set_func: GDExtensionScriptInstanceSet = @import("std").mem.zeroes(GDExtensionScriptInstanceSet),
    get_func: GDExtensionScriptInstanceGet = @import("std").mem.zeroes(GDExtensionScriptInstanceGet),
    get_property_list_func: GDExtensionScriptInstanceGetPropertyList = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyList),
    free_property_list_func: GDExtensionScriptInstanceFreePropertyList2 = @import("std").mem.zeroes(GDExtensionScriptInstanceFreePropertyList2),
    get_class_category_func: GDExtensionScriptInstanceGetClassCategory = @import("std").mem.zeroes(GDExtensionScriptInstanceGetClassCategory),
    property_can_revert_func: GDExtensionScriptInstancePropertyCanRevert = @import("std").mem.zeroes(GDExtensionScriptInstancePropertyCanRevert),
    property_get_revert_func: GDExtensionScriptInstancePropertyGetRevert = @import("std").mem.zeroes(GDExtensionScriptInstancePropertyGetRevert),
    get_owner_func: GDExtensionScriptInstanceGetOwner = @import("std").mem.zeroes(GDExtensionScriptInstanceGetOwner),
    get_property_state_func: GDExtensionScriptInstanceGetPropertyState = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyState),
    get_method_list_func: GDExtensionScriptInstanceGetMethodList = @import("std").mem.zeroes(GDExtensionScriptInstanceGetMethodList),
    free_method_list_func: GDExtensionScriptInstanceFreeMethodList2 = @import("std").mem.zeroes(GDExtensionScriptInstanceFreeMethodList2),
    get_property_type_func: GDExtensionScriptInstanceGetPropertyType = @import("std").mem.zeroes(GDExtensionScriptInstanceGetPropertyType),
    validate_property_func: GDExtensionScriptInstanceValidateProperty = @import("std").mem.zeroes(GDExtensionScriptInstanceValidateProperty),
    has_method_func: GDExtensionScriptInstanceHasMethod = @import("std").mem.zeroes(GDExtensionScriptInstanceHasMethod),
    get_method_argument_count_func: GDExtensionScriptInstanceGetMethodArgumentCount = @import("std").mem.zeroes(GDExtensionScriptInstanceGetMethodArgumentCount),
    call_func: GDExtensionScriptInstanceCall = @import("std").mem.zeroes(GDExtensionScriptInstanceCall),
    notification_func: GDExtensionScriptInstanceNotification2 = @import("std").mem.zeroes(GDExtensionScriptInstanceNotification2),
    to_string_func: GDExtensionScriptInstanceToString = @import("std").mem.zeroes(GDExtensionScriptInstanceToString),
    refcount_incremented_func: GDExtensionScriptInstanceRefCountIncremented = @import("std").mem.zeroes(GDExtensionScriptInstanceRefCountIncremented),
    refcount_decremented_func: GDExtensionScriptInstanceRefCountDecremented = @import("std").mem.zeroes(GDExtensionScriptInstanceRefCountDecremented),
    get_script_func: GDExtensionScriptInstanceGetScript = @import("std").mem.zeroes(GDExtensionScriptInstanceGetScript),
    is_placeholder_func: GDExtensionScriptInstanceIsPlaceholder = @import("std").mem.zeroes(GDExtensionScriptInstanceIsPlaceholder),
    set_fallback_func: GDExtensionScriptInstanceSet = @import("std").mem.zeroes(GDExtensionScriptInstanceSet),
    get_fallback_func: GDExtensionScriptInstanceGet = @import("std").mem.zeroes(GDExtensionScriptInstanceGet),
    get_language_func: GDExtensionScriptInstanceGetLanguage = @import("std").mem.zeroes(GDExtensionScriptInstanceGetLanguage),
    free_func: GDExtensionScriptInstanceFree = @import("std").mem.zeroes(GDExtensionScriptInstanceFree),
};
pub const GDExtensionWorkerThreadPoolGroupTask = ?*const fn (?*anyopaque, u32) callconv(.c) void;
pub const GDExtensionWorkerThreadPoolTask = ?*const fn (?*anyopaque) callconv(.c) void;
pub const GDEXTENSION_INITIALIZATION_CORE: c_int = 0;
pub const GDEXTENSION_INITIALIZATION_SERVERS: c_int = 1;
pub const GDEXTENSION_INITIALIZATION_SCENE: c_int = 2;
pub const GDEXTENSION_INITIALIZATION_EDITOR: c_int = 3;
pub const GDEXTENSION_MAX_INITIALIZATION_LEVEL: c_int = 4;
pub const GDExtensionInitializationLevel = c_uint;
pub const GDExtensionInitializeCallback = ?*const fn (?*anyopaque, GDExtensionInitializationLevel) callconv(.c) void;
pub const GDExtensionDeinitializeCallback = ?*const fn (?*anyopaque, GDExtensionInitializationLevel) callconv(.c) void;
pub const GDExtensionInitialization = extern struct {
    minimum_initialization_level: GDExtensionInitializationLevel = @import("std").mem.zeroes(GDExtensionInitializationLevel),
    userdata: ?*anyopaque = @import("std").mem.zeroes(?*anyopaque),
    initialize: GDExtensionInitializeCallback = @import("std").mem.zeroes(GDExtensionInitializeCallback),
    deinitialize: GDExtensionDeinitializeCallback = @import("std").mem.zeroes(GDExtensionDeinitializeCallback),
};
pub const GDExtensionInterfaceFunctionPtr = ?*const fn (...) callconv(.c) void;
pub const GDExtensionInterfaceGetProcAddress = ?*const fn ([*c]const u8) callconv(.c) GDExtensionInterfaceFunctionPtr;
pub const GDExtensionInitializationFunction = ?*const fn (GDExtensionInterfaceGetProcAddress, GDExtensionClassLibraryPtr, [*c]GDExtensionInitialization) callconv(.c) GDExtensionBool;
pub const GDExtensionGodotVersion = extern struct {
    major: u32 = @import("std").mem.zeroes(u32),
    minor: u32 = @import("std").mem.zeroes(u32),
    patch: u32 = @import("std").mem.zeroes(u32),
    string: [*c]const u8 = @import("std").mem.zeroes([*c]const u8),
};
pub const GDExtensionGodotVersion2 = extern struct {
    major: u32 = @import("std").mem.zeroes(u32),
    minor: u32 = @import("std").mem.zeroes(u32),
    patch: u32 = @import("std").mem.zeroes(u32),
    hex: u32 = @import("std").mem.zeroes(u32),
    status: [*c]const u8 = @import("std").mem.zeroes([*c]const u8),
    build: [*c]const u8 = @import("std").mem.zeroes([*c]const u8),
    hash: [*c]const u8 = @import("std").mem.zeroes([*c]const u8),
    timestamp: u64 = @import("std").mem.zeroes(u64),
    string: [*c]const u8 = @import("std").mem.zeroes([*c]const u8),
};
pub const GDExtensionMainLoopStartupCallback = ?*const fn (...) callconv(.c) void;
pub const GDExtensionMainLoopShutdownCallback = ?*const fn (...) callconv(.c) void;
pub const GDExtensionMainLoopFrameCallback = ?*const fn (...) callconv(.c) void;
pub const GDExtensionMainLoopCallbacks = extern struct {
    startup_func: GDExtensionMainLoopStartupCallback = @import("std").mem.zeroes(GDExtensionMainLoopStartupCallback),
    shutdown_func: GDExtensionMainLoopShutdownCallback = @import("std").mem.zeroes(GDExtensionMainLoopShutdownCallback),
    frame_func: GDExtensionMainLoopFrameCallback = @import("std").mem.zeroes(GDExtensionMainLoopFrameCallback),
};
pub const GDExtensionInterfaceGetGodotVersion = ?*const fn ([*c]GDExtensionGodotVersion) callconv(.c) void;
pub const GDExtensionInterfaceGetGodotVersion2 = ?*const fn ([*c]GDExtensionGodotVersion2) callconv(.c) void;
pub const GDExtensionInterfaceMemAlloc = ?*const fn (usize) callconv(.c) ?*anyopaque;
pub const GDExtensionInterfaceMemRealloc = ?*const fn (?*anyopaque, usize) callconv(.c) ?*anyopaque;
pub const GDExtensionInterfaceMemFree = ?*const fn (?*anyopaque) callconv(.c) void;
pub const GDExtensionInterfacePrintError = ?*const fn ([*c]const u8, [*c]const u8, [*c]const u8, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfacePrintErrorWithMessage = ?*const fn ([*c]const u8, [*c]const u8, [*c]const u8, [*c]const u8, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfacePrintWarning = ?*const fn ([*c]const u8, [*c]const u8, [*c]const u8, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfacePrintWarningWithMessage = ?*const fn ([*c]const u8, [*c]const u8, [*c]const u8, [*c]const u8, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfacePrintScriptError = ?*const fn ([*c]const u8, [*c]const u8, [*c]const u8, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfacePrintScriptErrorWithMessage = ?*const fn ([*c]const u8, [*c]const u8, [*c]const u8, [*c]const u8, i32, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceGetNativeStructSize = ?*const fn (GDExtensionConstStringNamePtr) callconv(.c) u64;
pub const GDExtensionInterfaceVariantNewCopy = ?*const fn (GDExtensionUninitializedVariantPtr, GDExtensionConstVariantPtr) callconv(.c) void;
pub const GDExtensionInterfaceVariantNewNil = ?*const fn (GDExtensionUninitializedVariantPtr) callconv(.c) void;
pub const GDExtensionInterfaceVariantDestroy = ?*const fn (GDExtensionVariantPtr) callconv(.c) void;
pub const GDExtensionInterfaceVariantCall = ?*const fn (GDExtensionVariantPtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionUninitializedVariantPtr, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionInterfaceVariantCallStatic = ?*const fn (GDExtensionVariantType, GDExtensionConstStringNamePtr, [*c]const GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionUninitializedVariantPtr, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionInterfaceVariantEvaluate = ?*const fn (GDExtensionVariantOperator, GDExtensionConstVariantPtr, GDExtensionConstVariantPtr, GDExtensionUninitializedVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantSet = ?*const fn (GDExtensionVariantPtr, GDExtensionConstVariantPtr, GDExtensionConstVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantSetNamed = ?*const fn (GDExtensionVariantPtr, GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantSetKeyed = ?*const fn (GDExtensionVariantPtr, GDExtensionConstVariantPtr, GDExtensionConstVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantSetIndexed = ?*const fn (GDExtensionVariantPtr, GDExtensionInt, GDExtensionConstVariantPtr, [*c]GDExtensionBool, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantGet = ?*const fn (GDExtensionConstVariantPtr, GDExtensionConstVariantPtr, GDExtensionUninitializedVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantGetNamed = ?*const fn (GDExtensionConstVariantPtr, GDExtensionConstStringNamePtr, GDExtensionUninitializedVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantGetKeyed = ?*const fn (GDExtensionConstVariantPtr, GDExtensionConstVariantPtr, GDExtensionUninitializedVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantGetIndexed = ?*const fn (GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionUninitializedVariantPtr, [*c]GDExtensionBool, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantIterInit = ?*const fn (GDExtensionConstVariantPtr, GDExtensionUninitializedVariantPtr, [*c]GDExtensionBool) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantIterNext = ?*const fn (GDExtensionConstVariantPtr, GDExtensionVariantPtr, [*c]GDExtensionBool) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantIterGet = ?*const fn (GDExtensionConstVariantPtr, GDExtensionVariantPtr, GDExtensionUninitializedVariantPtr, [*c]GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantHash = ?*const fn (GDExtensionConstVariantPtr) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceVariantRecursiveHash = ?*const fn (GDExtensionConstVariantPtr, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceVariantHashCompare = ?*const fn (GDExtensionConstVariantPtr, GDExtensionConstVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantBooleanize = ?*const fn (GDExtensionConstVariantPtr) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantDuplicate = ?*const fn (GDExtensionConstVariantPtr, GDExtensionVariantPtr, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceVariantStringify = ?*const fn (GDExtensionConstVariantPtr, GDExtensionStringPtr) callconv(.c) void;
pub const GDExtensionInterfaceVariantGetType = ?*const fn (GDExtensionConstVariantPtr) callconv(.c) GDExtensionVariantType;
pub const GDExtensionInterfaceVariantHasMethod = ?*const fn (GDExtensionConstVariantPtr, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantHasMember = ?*const fn (GDExtensionVariantType, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantHasKey = ?*const fn (GDExtensionConstVariantPtr, GDExtensionConstVariantPtr, [*c]GDExtensionBool) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantGetObjectInstanceId = ?*const fn (GDExtensionConstVariantPtr) callconv(.c) GDObjectInstanceID;
pub const GDExtensionInterfaceVariantGetTypeName = ?*const fn (GDExtensionVariantType, GDExtensionUninitializedStringPtr) callconv(.c) void;
pub const GDExtensionInterfaceVariantCanConvert = ?*const fn (GDExtensionVariantType, GDExtensionVariantType) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceVariantCanConvertStrict = ?*const fn (GDExtensionVariantType, GDExtensionVariantType) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceGetVariantFromTypeConstructor = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionVariantFromTypeConstructorFunc;
pub const GDExtensionInterfaceGetVariantToTypeConstructor = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionTypeFromVariantConstructorFunc;
pub const GDExtensionInterfaceGetVariantGetInternalPtrFunc = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionVariantGetInternalPtrFunc;
pub const GDExtensionInterfaceVariantGetPtrOperatorEvaluator = ?*const fn (GDExtensionVariantOperator, GDExtensionVariantType, GDExtensionVariantType) callconv(.c) GDExtensionPtrOperatorEvaluator;
pub const GDExtensionInterfaceVariantGetPtrBuiltinMethod = ?*const fn (GDExtensionVariantType, GDExtensionConstStringNamePtr, GDExtensionInt) callconv(.c) GDExtensionPtrBuiltInMethod;
pub const GDExtensionInterfaceVariantGetPtrConstructor = ?*const fn (GDExtensionVariantType, i32) callconv(.c) GDExtensionPtrConstructor;
pub const GDExtensionInterfaceVariantGetPtrDestructor = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionPtrDestructor;
pub const GDExtensionInterfaceVariantConstruct = ?*const fn (GDExtensionVariantType, GDExtensionUninitializedVariantPtr, [*c]const GDExtensionConstVariantPtr, i32, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionInterfaceVariantGetPtrSetter = ?*const fn (GDExtensionVariantType, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionPtrSetter;
pub const GDExtensionInterfaceVariantGetPtrGetter = ?*const fn (GDExtensionVariantType, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionPtrGetter;
pub const GDExtensionInterfaceVariantGetPtrIndexedSetter = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionPtrIndexedSetter;
pub const GDExtensionInterfaceVariantGetPtrIndexedGetter = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionPtrIndexedGetter;
pub const GDExtensionInterfaceVariantGetPtrKeyedSetter = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionPtrKeyedSetter;
pub const GDExtensionInterfaceVariantGetPtrKeyedGetter = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionPtrKeyedGetter;
pub const GDExtensionInterfaceVariantGetPtrKeyedChecker = ?*const fn (GDExtensionVariantType) callconv(.c) GDExtensionPtrKeyedChecker;
pub const GDExtensionInterfaceVariantGetConstantValue = ?*const fn (GDExtensionVariantType, GDExtensionConstStringNamePtr, GDExtensionUninitializedVariantPtr) callconv(.c) void;
pub const GDExtensionInterfaceVariantGetPtrUtilityFunction = ?*const fn (GDExtensionConstStringNamePtr, GDExtensionInt) callconv(.c) GDExtensionPtrUtilityFunction;
pub const GDExtensionInterfaceStringNewWithLatin1Chars = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const u8) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithUtf8Chars = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const u8) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithUtf16Chars = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const char16_t) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithUtf32Chars = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const char32_t) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithWideChars = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const wchar_t) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithLatin1CharsAndLen = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const u8, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithUtf8CharsAndLen = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const u8, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithUtf8CharsAndLen2 = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const u8, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringNewWithUtf16CharsAndLen = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const char16_t, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithUtf16CharsAndLen2 = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const char16_t, GDExtensionInt, GDExtensionBool) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringNewWithUtf32CharsAndLen = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const char32_t, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceStringNewWithWideCharsAndLen = ?*const fn (GDExtensionUninitializedStringPtr, [*c]const wchar_t, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceStringToLatin1Chars = ?*const fn (GDExtensionConstStringPtr, [*c]u8, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringToUtf8Chars = ?*const fn (GDExtensionConstStringPtr, [*c]u8, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringToUtf16Chars = ?*const fn (GDExtensionConstStringPtr, [*c]char16_t, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringToUtf32Chars = ?*const fn (GDExtensionConstStringPtr, [*c]char32_t, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringToWideChars = ?*const fn (GDExtensionConstStringPtr, [*c]wchar_t, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringOperatorIndex = ?*const fn (GDExtensionStringPtr, GDExtensionInt) callconv(.c) [*c]char32_t;
pub const GDExtensionInterfaceStringOperatorIndexConst = ?*const fn (GDExtensionConstStringPtr, GDExtensionInt) callconv(.c) [*c]const char32_t;
pub const GDExtensionInterfaceStringOperatorPlusEqString = ?*const fn (GDExtensionStringPtr, GDExtensionConstStringPtr) callconv(.c) void;
pub const GDExtensionInterfaceStringOperatorPlusEqChar = ?*const fn (GDExtensionStringPtr, char32_t) callconv(.c) void;
pub const GDExtensionInterfaceStringOperatorPlusEqCstr = ?*const fn (GDExtensionStringPtr, [*c]const u8) callconv(.c) void;
pub const GDExtensionInterfaceStringOperatorPlusEqWcstr = ?*const fn (GDExtensionStringPtr, [*c]const wchar_t) callconv(.c) void;
pub const GDExtensionInterfaceStringOperatorPlusEqC32str = ?*const fn (GDExtensionStringPtr, [*c]const char32_t) callconv(.c) void;
pub const GDExtensionInterfaceStringResize = ?*const fn (GDExtensionStringPtr, GDExtensionInt) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceStringNameNewWithLatin1Chars = ?*const fn (GDExtensionUninitializedStringNamePtr, [*c]const u8, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceStringNameNewWithUtf8Chars = ?*const fn (GDExtensionUninitializedStringNamePtr, [*c]const u8) callconv(.c) void;
pub const GDExtensionInterfaceStringNameNewWithUtf8CharsAndLen = ?*const fn (GDExtensionUninitializedStringNamePtr, [*c]const u8, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceXmlParserOpenBuffer = ?*const fn (GDExtensionObjectPtr, [*c]const u8, usize) callconv(.c) GDExtensionInt;
pub const GDExtensionInterfaceFileAccessStoreBuffer = ?*const fn (GDExtensionObjectPtr, [*c]const u8, u64) callconv(.c) void;
pub const GDExtensionInterfaceFileAccessGetBuffer = ?*const fn (GDExtensionConstObjectPtr, [*c]u8, u64) callconv(.c) u64;
pub const GDExtensionInterfaceImagePtrw = ?*const fn (GDExtensionObjectPtr) callconv(.c) [*c]u8;
pub const GDExtensionInterfaceImagePtr = ?*const fn (GDExtensionObjectPtr) callconv(.c) [*c]const u8;
pub const GDExtensionInterfaceWorkerThreadPoolAddNativeGroupTask = ?*const fn (GDExtensionObjectPtr, GDExtensionWorkerThreadPoolGroupTask, ?*anyopaque, c_int, c_int, GDExtensionBool, GDExtensionConstStringPtr) callconv(.c) i64;
pub const GDExtensionInterfaceWorkerThreadPoolAddNativeTask = ?*const fn (GDExtensionObjectPtr, GDExtensionWorkerThreadPoolTask, ?*anyopaque, GDExtensionBool, GDExtensionConstStringPtr) callconv(.c) i64;
pub const GDExtensionInterfacePackedByteArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) [*c]u8;
pub const GDExtensionInterfacePackedByteArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) [*c]const u8;
pub const GDExtensionInterfacePackedFloat32ArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) [*c]f32;
pub const GDExtensionInterfacePackedFloat32ArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) [*c]const f32;
pub const GDExtensionInterfacePackedFloat64ArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) [*c]f64;
pub const GDExtensionInterfacePackedFloat64ArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) [*c]const f64;
pub const GDExtensionInterfacePackedInt32ArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) [*c]i32;
pub const GDExtensionInterfacePackedInt32ArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) [*c]const i32;
pub const GDExtensionInterfacePackedInt64ArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) [*c]i64;
pub const GDExtensionInterfacePackedInt64ArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) [*c]const i64;
pub const GDExtensionInterfacePackedStringArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) GDExtensionStringPtr;
pub const GDExtensionInterfacePackedStringArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) GDExtensionStringPtr;
pub const GDExtensionInterfacePackedVector2ArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfacePackedVector2ArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfacePackedVector3ArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfacePackedVector3ArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfacePackedVector4ArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfacePackedVector4ArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfacePackedColorArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfacePackedColorArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) GDExtensionTypePtr;
pub const GDExtensionInterfaceArrayOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionInt) callconv(.c) GDExtensionVariantPtr;
pub const GDExtensionInterfaceArrayOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionInt) callconv(.c) GDExtensionVariantPtr;
pub const GDExtensionInterfaceArrayRef = ?*const fn (GDExtensionTypePtr, GDExtensionConstTypePtr) callconv(.c) void;
pub const GDExtensionInterfaceArraySetTyped = ?*const fn (GDExtensionTypePtr, GDExtensionVariantType, GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr) callconv(.c) void;
pub const GDExtensionInterfaceDictionaryOperatorIndex = ?*const fn (GDExtensionTypePtr, GDExtensionConstVariantPtr) callconv(.c) GDExtensionVariantPtr;
pub const GDExtensionInterfaceDictionaryOperatorIndexConst = ?*const fn (GDExtensionConstTypePtr, GDExtensionConstVariantPtr) callconv(.c) GDExtensionVariantPtr;
pub const GDExtensionInterfaceDictionarySetTyped = ?*const fn (GDExtensionTypePtr, GDExtensionVariantType, GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr, GDExtensionVariantType, GDExtensionConstStringNamePtr, GDExtensionConstVariantPtr) callconv(.c) void;
pub const GDExtensionInterfaceObjectMethodBindCall = ?*const fn (GDExtensionMethodBindPtr, GDExtensionObjectPtr, [*c]const GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionUninitializedVariantPtr, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionInterfaceObjectMethodBindPtrcall = ?*const fn (GDExtensionMethodBindPtr, GDExtensionObjectPtr, [*c]const GDExtensionConstTypePtr, GDExtensionTypePtr) callconv(.c) void;
pub const GDExtensionInterfaceObjectDestroy = ?*const fn (GDExtensionObjectPtr) callconv(.c) void;
pub const GDExtensionInterfaceGlobalGetSingleton = ?*const fn (GDExtensionConstStringNamePtr) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionInterfaceObjectGetInstanceBinding = ?*const fn (GDExtensionObjectPtr, ?*anyopaque, [*c]const GDExtensionInstanceBindingCallbacks) callconv(.c) ?*anyopaque;
pub const GDExtensionInterfaceObjectSetInstanceBinding = ?*const fn (GDExtensionObjectPtr, ?*anyopaque, ?*anyopaque, [*c]const GDExtensionInstanceBindingCallbacks) callconv(.c) void;
pub const GDExtensionInterfaceObjectFreeInstanceBinding = ?*const fn (GDExtensionObjectPtr, ?*anyopaque) callconv(.c) void;
pub const GDExtensionInterfaceObjectSetInstance = ?*const fn (GDExtensionObjectPtr, GDExtensionConstStringNamePtr, GDExtensionClassInstancePtr) callconv(.c) void;
pub const GDExtensionInterfaceObjectGetClassName = ?*const fn (GDExtensionConstObjectPtr, GDExtensionClassLibraryPtr, GDExtensionUninitializedStringNamePtr) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceObjectCastTo = ?*const fn (GDExtensionConstObjectPtr, ?*anyopaque) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionInterfaceObjectGetInstanceFromId = ?*const fn (GDObjectInstanceID) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionInterfaceObjectGetInstanceId = ?*const fn (GDExtensionConstObjectPtr) callconv(.c) GDObjectInstanceID;
pub const GDExtensionInterfaceObjectHasScriptMethod = ?*const fn (GDExtensionConstObjectPtr, GDExtensionConstStringNamePtr) callconv(.c) GDExtensionBool;
pub const GDExtensionInterfaceObjectCallScriptMethod = ?*const fn (GDExtensionObjectPtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionConstVariantPtr, GDExtensionInt, GDExtensionUninitializedVariantPtr, [*c]GDExtensionCallError) callconv(.c) void;
pub const GDExtensionInterfaceRefGetObject = ?*const fn (GDExtensionConstRefPtr) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionInterfaceRefSetObject = ?*const fn (GDExtensionRefPtr, GDExtensionObjectPtr) callconv(.c) void;
pub const GDExtensionInterfaceScriptInstanceCreate = ?*const fn ([*c]const GDExtensionScriptInstanceInfo, GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionScriptInstancePtr;
pub const GDExtensionInterfaceScriptInstanceCreate2 = ?*const fn ([*c]const GDExtensionScriptInstanceInfo2, GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionScriptInstancePtr;
pub const GDExtensionInterfaceScriptInstanceCreate3 = ?*const fn ([*c]const GDExtensionScriptInstanceInfo3, GDExtensionScriptInstanceDataPtr) callconv(.c) GDExtensionScriptInstancePtr;
pub const GDExtensionInterfacePlaceHolderScriptInstanceCreate = ?*const fn (GDExtensionObjectPtr, GDExtensionObjectPtr, GDExtensionObjectPtr) callconv(.c) GDExtensionScriptInstancePtr;
pub const GDExtensionInterfacePlaceHolderScriptInstanceUpdate = ?*const fn (GDExtensionScriptInstancePtr, GDExtensionConstTypePtr, GDExtensionConstTypePtr) callconv(.c) void;
pub const GDExtensionInterfaceObjectGetScriptInstance = ?*const fn (GDExtensionConstObjectPtr, GDExtensionObjectPtr) callconv(.c) GDExtensionScriptInstanceDataPtr;
pub const GDExtensionInterfaceObjectSetScriptInstance = ?*const fn (GDExtensionObjectPtr, GDExtensionScriptInstanceDataPtr) callconv(.c) void;
pub const GDExtensionInterfaceCallableCustomCreate = ?*const fn (GDExtensionUninitializedTypePtr, [*c]GDExtensionCallableCustomInfo) callconv(.c) void;
pub const GDExtensionInterfaceCallableCustomCreate2 = ?*const fn (GDExtensionUninitializedTypePtr, [*c]GDExtensionCallableCustomInfo2) callconv(.c) void;
pub const GDExtensionInterfaceCallableCustomGetUserData = ?*const fn (GDExtensionConstTypePtr, ?*anyopaque) callconv(.c) ?*anyopaque;
pub const GDExtensionInterfaceClassdbConstructObject = ?*const fn (GDExtensionConstStringNamePtr) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionInterfaceClassdbConstructObject2 = ?*const fn (GDExtensionConstStringNamePtr) callconv(.c) GDExtensionObjectPtr;
pub const GDExtensionInterfaceClassdbGetMethodBind = ?*const fn (GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, GDExtensionInt) callconv(.c) GDExtensionMethodBindPtr;
pub const GDExtensionInterfaceClassdbGetClassTag = ?*const fn (GDExtensionConstStringNamePtr) callconv(.c) ?*anyopaque;
pub const GDExtensionInterfaceClassdbRegisterExtensionClass = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionClassCreationInfo) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClass2 = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionClassCreationInfo2) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClass3 = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionClassCreationInfo3) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClass4 = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionClassCreationInfo4) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClass5 = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionClassCreationInfo5) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassMethod = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionClassMethodInfo) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassVirtualMethod = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionClassVirtualMethodInfo) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassIntegerConstant = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, GDExtensionInt, GDExtensionBool) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassProperty = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionPropertyInfo, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassPropertyIndexed = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionPropertyInfo, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassPropertyGroup = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringPtr, GDExtensionConstStringPtr) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassPropertySubgroup = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringPtr, GDExtensionConstStringPtr) callconv(.c) void;
pub const GDExtensionInterfaceClassdbRegisterExtensionClassSignal = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr, GDExtensionConstStringNamePtr, [*c]const GDExtensionPropertyInfo, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceClassdbUnregisterExtensionClass = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionConstStringNamePtr) callconv(.c) void;
pub const GDExtensionInterfaceGetLibraryPath = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionUninitializedStringPtr) callconv(.c) void;
pub const GDExtensionInterfaceEditorAddPlugin = ?*const fn (GDExtensionConstStringNamePtr) callconv(.c) void;
pub const GDExtensionInterfaceEditorRemovePlugin = ?*const fn (GDExtensionConstStringNamePtr) callconv(.c) void;
pub const GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8Chars = ?*const fn ([*c]const u8) callconv(.c) void;
pub const GDExtensionsInterfaceEditorHelpLoadXmlFromUtf8CharsAndLen = ?*const fn ([*c]const u8, GDExtensionInt) callconv(.c) void;
pub const GDExtensionInterfaceEditorRegisterGetClassesUsedCallback = ?*const fn (GDExtensionClassLibraryPtr, GDExtensionEditorGetClassesUsedCallback) callconv(.c) void;
pub const GDExtensionInterfaceRegisterMainLoopCallbacks = ?*const fn (GDExtensionClassLibraryPtr, [*c]const GDExtensionMainLoopCallbacks) callconv(.c) void;
